const Database = require("better-sqlite3");
const path = require("path");
const crypto = require("crypto");

const dbPath = path.resolve(__dirname, "dev.db");
const db = new Database(dbPath);

function genId() { return crypto.randomBytes(12).toString("hex"); }

// [ten, platform, linkProfile, sdt, ghiChu]
const kocs = [
  // ===== ĐÃ BOOK =====
  ["Huỳnh Anh","tiktok","","0774011065","ĐÃ BOOK | Cast: 400.000đ | 30 Ngô Quốc Trị, kv3-p5 tp VịThanh"],
  ["Quỳnh Anh uni","tiktok","","0961316906","ĐÃ BOOK | Cast: 1.500.000đ | 19 LÊ NGỌC HÂN, PHẠM ĐÌNH HỒ, HAI BÀ TRƯNG, HN"],
  ["Vi Thị Như Quỳnh","tiktok","","0965444790","ĐÃ BOOK | Cast: 2.500.000đ | Toà H3 Vinhome Ocean Park, Gia Lâm, Hà Nội"],
  ["NimDay","tiktok","","0963006483","ĐÃ BOOK | Cast: 800.000đ | Số 8 Quang Trung, phường Quang Trung, Hà Đông, Hà Nội"],
  ["Dương Xanh","tiktok","","0345600906","ĐÃ BOOK | Cast: 0đ | Sol Forest Ecopark, Xuân Quan, Văn Giang, Hưng Yên"],
  ["Cố Hữu Vi","tiktok","","0353088181","ĐÃ BOOK | Cast: 1.200.000đ | Golden House, Sunwah Pearl, 90 Nguyễn Hữu Cảnh, Bình Thạnh"],
  ["Mình là gấu","tiktok","","0354766295","ĐÃ BOOK | Cast: 0đ | Toà S111 Vinhomes Ocean Park, Đa Tốn, Gia Lâm, HN"],
  ["oanh lên đồ","tiktok","","0382270257","ĐÃ BOOK | Cast: 0đ | Số 7c đường A2 thôn 6, Cư Êbur, Buôn Mê Thuột, Đắk Lắk"],
  ["nga trik","tiktok","","0941413689","ĐÃ BOOK | Cast: 2.300.000đ | S215 Vinhomes Ocean Park, Đa Tốn, Gia Lâm, HN"],
  ["Gia Hân Booking","tiktok","","0387016298","ĐÃ BOOK | Cast: 1.800.000đ | 588 Phan Văn Trị, phường 7, quận Gò Vấp, HCM"],
  ["Thanh Đây Nè","tiktok","","0964561609","ĐÃ BOOK | Cast: 500.000đ | Chung cư Beasky Đại Kim, Hoàng Mai, HN"],
  ["Nguyễn Thị Huyền","tiktok","","0817725938","ĐÃ BOOK | Cast: 500.000đ | Sean spa, chung cư THT New City, Hoài Đức, HN"],
  ["nguyn.macdo","tiktok","https://www.tiktok.com/@nguyn.macdo","0779964157","ĐÃ BOOK | Cast: 200.000đ | Ct9 chung cư The Ori Garden, Hoà Hiệp Nam, Liên Chiểu, Đà Nẵng"],
  ["ei mochei","tiktok","https://www.tiktok.com/@mochei_ootd","0376097142","ĐÃ BOOK | Cast: 300.000đ | S305 Vinhomes Grand Park, Long Thạnh Mỹ, Thủ Đức"],
  ["2Chijbell","tiktok","https://www.tiktok.com/@2chijbell","0975889034","ĐÃ BOOK | Cast: 500.000đ | 182/10/13A Hồ Văn Long, Bình Hưng Hoà B, Bình Tân, HCM"],
  ["Jade","tiktok","https://www.tiktok.com/@jade.ngthuy","0833414625","ĐÃ BOOK | Cast: 700.000đ | Số 21 ngõ 40 Đan Khê, Di Trạch, Hoài Đức"],
  ["Nước lọc 7 mào","tiktok","https://www.tiktok.com/@nuocloc7mao","0343608098","ĐÃ BOOK | Cast: 400.000đ | Nhà trọ Tuyến Lĩnh, 38t/7, khu vực 3, An Khánh, Ninh Kiều, Cần Thơ"],
  ["Minh Tâm","tiktok","","0707917487","ĐÃ BOOK | Cast: 0đ | 112 Huỳnh Ngọc Đủ, Hoà Xuân, Cẩm Lệ, Đà Nẵng"],
  ["Anh Thanh","tiktok","","0347096997","ĐÃ BOOK | Cast: 0đ | Số 36 ngõ 51 Tam Khương, Khương Thượng, Đống Đa, HN"],
  ["40kg's outfit","tiktok","https://www.tiktok.com/@aophitofthuyn","0362972417","ĐÃ BOOK | Cast: 200.000đ | 28 Đồng Cổ, Bưởi, Tây Hồ, HN"],
  ["1m49macdoxinh","tiktok","https://www.tiktok.com/@1m49macdoxinh","0357996505","ĐÃ BOOK | Cast: 0đ | 19 Nguyễn Trung Ngạn, Lỗ Xá, Nhân Hòa, Mỹ Hào, Hưng Yên"],
  ["Quỳnh Aggg","tiktok","https://www.tiktok.com/@quynhanhlendo_","0965208362","ĐÃ BOOK | Cast: 300.000đ | Toà GS3 Vinhomes Smart City, Tây Mỗ, Nam Từ Liêm, HN"],
  ["yen.nhi.sayhi","tiktok","https://www.tiktok.com/@yen.nhi.sayhi","0924132678","ĐÃ BOOK | Cast: 400.000đ | Toà B Paragon, 86 Duy Tân, Dịch Vọng Hậu, Cầu Giấy"],
  ["Lan Vy Xinh Đẹp","tiktok","https://www.tiktok.com/@vyluckily","0984444371","ĐÃ BOOK | Cast: 800.000đ | 9-11 Nguyễn Quý Yêm, An Lạc, Bình Tân, HCM"],
  ["Traggggg Phmm","tiktok","https://www.tiktok.com/@50kg3","0968769589","ĐÃ BOOK | Cast: 1.000.000đ | Số 25 ngách 64 ngõ 49 Huỳnh Thúc Kháng, Láng Hạ, Đống Đa, HN"],
  ["Vy Max","tiktok","https://www.tiktok.com/@vymaxiee","0767895527","ĐÃ BOOK | Cast: 1.500.000đ | 673/8b tỉnh lộ 10, Bình Trị Đông B, Bình Tân, HCM"],
  ["Tiểu Lann","tiktok","https://www.tiktok.com/@tieulannnnn","0392196384","ĐÃ BOOK | Cast: 900.000đ | Toà B NT Home, 109 phố Nhổn, Phương Canh, Nam Từ Liêm, HN"],
  ["Chu Phương Luyến","tiktok","https://www.tiktok.com/@chuphuongluyen","0334829584","ĐÃ BOOK | Cast: 750.000đ | H1 Haven Park, Ecopark, Xuân Quan, Văn Giang, Hưng Yên"],
  ["DuDương dáng","tiktok","https://www.tiktok.com/@du_duong_tap_phoi_do","0389067395","ĐÃ BOOK | Cast: 1.200.000đ | Số 125 ngõ 189 Nguyễn Ngọc Vũ, Trung Hoà, Cầu Giấy, HN"],
  ["hthuy_toi","tiktok","https://www.tiktok.com/@touithuy","0378721159","ĐÃ BOOK | Cast: 850.000đ | Căn CX14-49 đường Cọ Xanh, Vinhomes Ocean Park 2, Văn Giang, Hưng Yên"],
  ["Cheang","tiktok","https://www.tiktok.com/@couplekiukiu","0913051251","ĐÃ BOOK | Cast: 300.000đ | 10/2 Đường số 9, Khu phố 4, An Khánh, Quận 2, Thủ Đức"],
  ["Hương TRần","tiktok","https://www.tiktok.com/@huongtran129","0989933754","ĐÃ BOOK | Cast: 1.000.000đ | Tòa R1.03 The Zenpark, Vinhomes Ocean Park, Gia Lâm, HN"],
  ["tettanic","tiktok","https://www.tiktok.com/@tettanic","0904984048","ĐÃ BOOK | Cast: 1.000.000đ | Số 16 ngách 134 ngõ 173 Hoàng Hoa Thám, Ngọc Hà, Ba Đình, HN"],
  ["chị nấm m48","tiktok","https://www.tiktok.com/@chi.nam.m48","0985053854","ĐÃ BOOK | Cast: 1.000.000đ | Grand Pex House, Thôn 3, Thạch Hoà, Thạch Thất, HN"],
  ["snowy_outfit","tiktok","https://www.tiktok.com/@snowy_outfit","0967369724","ĐÃ BOOK | Cast: 0đ | 259 Trần Hưng Đạo, Cô Giang, Quận 1, HCM"],
  ["Di Lưu","tiktok","https://www.tiktok.com/@dilluu0","0795821269","ĐÃ BOOK | Cast: 450.000đ | Ngõ 259 ngách 28 số 7b Vĩnh Hưng, Hoàng Mai, HN"],
  ["ngn.mt.53","tiktok","https://www.tiktok.com/@ngn.mt.53","0353594517","ĐÃ BOOK | Cast: 0đ | Số nhà 20 ngách 106 ngõ 25 Phú Minh, Minh Khai, Bắc Từ Liêm, HN"],
  ["_trchauquin","tiktok","https://www.tiktok.com/@trchauquin","","ĐÃ BOOK | Cast: 400.000đ"],
  ["mitbigsize","tiktok","https://www.tiktok.com/@mitbigsize_","","ĐÃ BOOK | Cast: 0đ"],
  ["cachetkute","tiktok","https://www.tiktok.com/@cachepkute","0933423014","ĐÃ BOOK | Cast: 0đ | A4/18A đường Liên Ấp 123, Tân Vĩnh Lộc, Vĩnh Lộc B, Bình Chánh, HCM"],
  ["tangvyhai","tiktok","https://www.tiktok.com/@tangvyhai","","ĐÃ BOOK | Cast: 350.000đ"],
  ["congchuabeo_68","tiktok","https://www.tiktok.com/@congchuabeo_68","","ĐÃ BOOK | Cast: 100.000đ"],
  ["__lynxx","tiktok","https://www.tiktok.com/@__lynxx","","ĐÃ BOOK | Cast: 700.000đ"],
  ["Trinh Thi Thuy Nhung","tiktok","https://www.tiktok.com/@gnuhn.236","","ĐÃ BOOK | Cast: 0đ"],
  ["_tieniuday","tiktok","https://www.tiktok.com/@_tieniuday","0934915314","ĐÃ BOOK | Cast: 400.000đ | 272 Nguyễn Phước Nguyên, An Khê, Thanh Khê, Đà Nẵng"],
  ["Thì Dưn","tiktok","https://www.tiktok.com/@th.dn9604","","ĐÃ BOOK | Cast: 300k(có giỏ)-500k(không giỏ) | BOOK k cần giỏ"],
  ["dmthu0410","tiktok","https://www.tiktok.com/@dmthu0410","","ĐÃ BOOK | Cast: 500.000đ"],
  ["KaiXin tập phối đồ","tiktok","https://www.tiktok.com/@kaixin.tp.phi","0778381763","ĐÃ BOOK | Cast: 0đ | Số nhà 28 ngõ 2 thôn Hải An, Quảng Thành, Hải Hà, Quảng Ninh"],
  ["Khánh Nhi","tiktok","https://www.tiktok.com/@lhkhanhnhii","","ĐÃ BOOK | Cast: 0đ"],
  ["Babysix","tiktok","https://www.tiktok.com/@babysix_06","","ĐÃ BOOK | Cast: 400.000đ | Lần 1"],
  ["Linhh Nguyen Bigsize","tiktok","https://www.tiktok.com/@linhnguyenbigsize","","ĐÃ BOOK | Cast: 0đ | OK NẾU BOOKING FREE"],
  ["Làng Xì Trum","tiktok","https://www.tiktok.com/@langxitrum.vn","0945986051","ĐÃ BOOK | Cast: 0đ | Lô S12 Đường Số 16, An Đông, TP Huế"],
  ["TuyetDaooo","tiktok","https://www.tiktok.com/@2911tdaooo__","0339890733","ĐÃ BOOK | Cast: 350k/1 người - 650k/couple | Lần 2 | 69 Trương Văn Hải, Tăng Nhơn Phú B, Thủ Đức"],
  ["T. Hà","tiktok","https://www.tiktok.com/@thuhareview08","0352254072","ĐÃ BOOK | Cast: 700.000đ | Lần 1 | Toà Sa5 Vinsmart Tây Mỗ, Nam Từ Liêm, HN"],
  ["Lady Chân To","tiktok","https://www.tiktok.com/@ladychanto","","ĐÃ BOOK | Cast: 0đ"],
  ["HanhDung","tiktok","https://www.tiktok.com/@bedun06","","ĐÃ BOOK | Cast: 0đ"],
  ["It's Búnn","tiktok","https://www.tiktok.com/@buns_day","","ĐÃ BOOK | Cast: 500.000đ"],
  ["CHANG ANH review tấu hề","tiktok","https://www.tiktok.com/@changanhreview1512","","ĐÃ BOOK | Cast: 0đ"],
  ["Yến Mẫn Xinhh","tiktok","https://www.tiktok.com/@yenmannxinhh","","ĐÃ BOOK | Cast: 350.000đ"],
  ["hanwg24","tiktok","https://www.tiktok.com/@hanwg24","","ĐÃ BOOK | Cast: 0đ"],

  // ===== CHƯA BOOK =====
  ["Enpii","tiktok","https://www.tiktok.com/@n_phuongz","","CHƯA BOOK | Cast: 1.500.000đ"],
  ["Xalach_","tiktok","https://www.tiktok.com/@xalach1010","","CHƯA BOOK | Cast: 1.000.000đ"],
  ["mét rưỡi mặt gì","tiktok","https://www.tiktok.com/@tao_review11","","CHƯA BOOK | Cast: 2.500.000đ"],
  ["lnch.19","tiktok","https://www.tiktok.com/@lnch.19","","CHƯA BOOK | Cast: 1.400.000đ"],
  ["langxitrum.vn","tiktok","https://www.tiktok.com/@langxitrum.vn","","CHƯA BOOK | Chưa liên hệ được"],
  ["n_phuongz","tiktok","https://www.tiktok.com/@n_phuongz","","CHƯA BOOK | Cast: 1.500.000đ"],
  ["Bella người đẹp","tiktok","https://www.tiktok.com/@bellasaigon222","","CHƯA BOOK | Cast: 1.500.000đ"],
  ["myduyendao.23","tiktok","https://www.tiktok.com/@myduyendao.23","0378256582","CHƯA BOOK | Cast: 0đ"],
  ["trang lên đồ","tiktok","https://www.tiktok.com/@27thutrang.review","","CHƯA BOOK | Cast: 200.000đ"],
  ["m5cutenho","tiktok","https://www.tiktok.com/@m5cutenho","0795821269","CHƯA BOOK | Cast: 0đ lần đầu, có hiệu quả lần sau mới tính"],
  ["meidei.review","tiktok","https://www.tiktok.com/@meidei.review","","CHƯA BOOK | Đang tìm cách liên hệ | Kết Bạn"],
  ["thori","tiktok","https://www.tiktok.com/@thorriibae","","CHƯA BOOK | Chưa liên hệ được"],
  ["krixietapphoi","tiktok","https://www.tiktok.com/@krixietapphoi","","CHƯA BOOK | Lần 1"],
  ["t.hawgf","tiktok","https://www.tiktok.com/@t.hawgf","","CHƯA BOOK | Lần 1"],
  ["pum.macdo","tiktok","https://www.tiktok.com/@pum.macdo","","CHƯA BOOK | Đang tìm cách liên hệ"],
  ["thutothon999","tiktok","https://www.tiktok.com/@thutothon999","","CHƯA BOOK | Lần 1"],
  ["hoexinhhon_nef","tiktok","https://www.tiktok.com/@hoexinhhon_nef","","CHƯA BOOK | Đang tìm cách liên hệ"],
  ["babyechmap","tiktok","https://www.tiktok.com/@babyechmap","","CHƯA BOOK | Đang tìm cách liên hệ"],
  ["nhi bae nè","tiktok","https://www.tiktok.com/@nhinhi.2804","","CHƯA BOOK | Cast: 200.000đ"],
  ["himinhnghi_99","tiktok","https://www.tiktok.com/@himinhnghi_99","","CHƯA BOOK | Cast: 500.000đ"],
  ["mét năm ra đường","tiktok","https://www.tiktok.com/@outfit_linhchi","","CHƯA BOOK | Cast: 1.400.000đ | Được nhưng đắt, chuyển đổi kém"],
  ["thwxauxi","tiktok","https://www.tiktok.com/@thwxauxi","","CHƯA BOOK | Cast: 500.000đ"],
  ["quynnhnga","tiktok","https://www.tiktok.com/@quynnhnga_","","CHƯA BOOK | Cast: 450.000đ | Cũng được thôi"],
  ["Dinh Quynh Lan","tiktok","https://www.tiktok.com/@dinhquynhlan_","","CHƯA BOOK | Cast: 1.200.000đ | Video tầm 10-20k, giá cao"],
  ["pé đa","tiktok","https://www.tiktok.com/@anhpham53","","CHƯA BOOK | Gửi tặng đồ"],
  ["1m68 tập phối đồ","tiktok","https://www.tiktok.com/@haianhh464","","CHƯA BOOK | Đang tìm cách liên hệ"],
  ["anhnguyet.04","tiktok","https://www.tiktok.com/@anhnguyet.04","","CHƯA BOOK"],
  ["yunchen2809","tiktok","https://www.tiktok.com/@yunchen2809","","CHƯA BOOK | Không nhận | OKE"],
  ["dtpa_wearing","tiktok","https://www.tiktok.com/@dtpa.wearing","","CHƯA BOOK | Chưa phản hồi | CHECK LẠI"],
  ["thwyn_","tiktok","https://www.tiktok.com/@thwyn_","","CHƯA BOOK | Không nhận quần jean | Oke"],
  ["optimusap","tiktok","https://www.tiktok.com/@optimusap","","CHƯA BOOK | Chưa phản hồi | LH lại"],
  ["Muội mặc gì?","tiktok","https://www.tiktok.com/@muoimacgi","","CHƯA BOOK | Chưa phản hồi | LH lại"],
  ["miihanhdepgai","tiktok","https://www.tiktok.com/@mhnhnguynth144","","CHƯA BOOK | Cast: 0đ"],
  ["feijinn","tiktok","https://www.tiktok.com/@feijinnn","","CHƯA BOOK | Không nhận | Sẽ LH lại sau"],
  ["nguyetthanhlatuiii","tiktok","https://www.tiktok.com/@nguyetthanhlatuiii","","CHƯA BOOK | Chưa phản hồi | Hỏi giá lại"],
  ["phanhxt","tiktok","https://www.tiktok.com/@phuowganhhh","","CHƯA BOOK | LH lại"],
  ["nkhaaiiii","tiktok","https://www.tiktok.com/@nkhaaiiii","","CHƯA BOOK | BOOK | Email: hellonhankhaai@gmail.com, đã gửi mail chưa phản hồi"],
  ["Huongmaiphm","tiktok","https://www.tiktok.com/@huongmaiphm","","CHƯA BOOK | Đã LH chưa phản hồi"],
  ["martiniz","tiktok","https://www.tiktok.com/@martiniz2110","","CHƯA BOOK | Cast: 650.000đ | Đắt"],
  ["trà dâu","tiktok","https://www.tiktok.com/@chuylinhdei","","CHƯA BOOK | Cast: 700k/2 set, 1 set 1tr | Nick phụ của __lynxx đã book"],
  ["homnaytuidep","tiktok","https://www.tiktok.com/@homnaytuidep","","CHƯA BOOK | Chỉ lên kiểu ghép ảnh, không quay review"],
  ["Sunn","tiktok","https://www.tiktok.com/@hthnxxxx","","CHƯA BOOK | Cast: 350.000đ | Không có view"],
  ["hanieyeee_","tiktok","https://www.tiktok.com/@hanieyeee_","","CHƯA BOOK | OK, check giá | Đã LH Tik chưa phản hồi"],
  ["cloudyy_186","tiktok","https://www.tiktok.com/@cloudyy_186","","CHƯA BOOK"],
  ["beloved.68","tiktok","https://www.tiktok.com/@beloved.68","","CHƯA BOOK"],
  ["Tiểu Ái","tiktok","https://www.tiktok.com/@tieuai2406","","CHƯA BOOK"],
  ["Quỳnh Bùi","tiktok","https://www.tiktok.com/@imnhwuynh","","CHƯA BOOK | Cast: 150.000đ"],
  ["Lenvy","tiktok","https://www.tiktok.com/@lennie0306","","CHƯA BOOK"],
  ["Thảo Mập Bigsize BG","tiktok","https://www.tiktok.com/@thaomapbigsize9x","","CHƯA BOOK"],
  ["chang thèm bún bò","tiktok","https://www.tiktok.com/@lhkhanhnhii","","CHƯA BOOK"],
  ["Bi chiến","tiktok","https://www.tiktok.com/@bichien29","","CHƯA BOOK"],
  ["Meow M53","tiktok","https://www.tiktok.com/@meodao486","","CHƯA BOOK"],
  ["mmeiii14","tiktok","https://www.tiktok.com/@mmeiii14","","CHƯA BOOK"],
  ["ptanhhh01","tiktok","https://www.tiktok.com/@chanhriviuuu","","CHƯA BOOK"],
  ["Thaomoon đi đâu đấyy?","tiktok","https://www.tiktok.com/@_th.moon203","","CHƯA BOOK"],
  ["Ngọc Phương Review","tiktok","https://www.tiktok.com/@ngocphuongg.review","","CHƯA BOOK"],
  ["Cii","tiktok","https://www.tiktok.com/@phuong.cii","","CHƯA BOOK"],
  ["nuocloc7mao","tiktok","https://www.tiktok.com/@nuocloc7mao","","CHƯA BOOK"],
  ["Thu Tốt Hơn","tiktok","https://www.tiktok.com/@thutothon999","","CHƯA BOOK"],
  ["Dainy","tiktok","https://www.tiktok.com/@dainy972","","CHƯA BOOK"],
  ["Ce gen Z","shopee","https://shopee.vn/product/37169157/42072345997/","","CHƯA BOOK | Cast: 500.000đ"],
  ["Trúc Trúc","tiktok","https://www.tiktok.com/@holoyaaa_","","CHƯA BOOK | Cast: 500.000đ"],
  ["điệu ơi là điệu","tiktok","https://www.tiktok.com/@knganz","","CHƯA BOOK"],
  ["Tú Linh","tiktok","https://www.tiktok.com/@buniuiu","","CHƯA BOOK"],
  ["Lady chân to","tiktok","https://www.tiktok.com/@ladychanto","","CHƯA BOOK"],
  ["Trinhpanda","tiktok","https://www.tiktok.com/@trinhpandatiktok","","CHƯA BOOK"],
  ["Nguyễn Hà Thu (mẹ Leo)","tiktok","https://www.tiktok.com/@hathuuu1610","","CHƯA BOOK"],
  ["lizzie","tiktok","https://www.tiktok.com/@lizzie_phmm","","CHƯA BOOK"],
  ["Cún Trendy","tiktok","https://www.tiktok.com/@cuntrendy","","CHƯA BOOK"],
  ["maingocneee","tiktok","https://www.tiktok.com/@maingocneee13","","CHƯA BOOK"],
  ["Phan Lem m49 mặc gì?","tiktok","https://www.tiktok.com/@phanlem_","","CHƯA BOOK"],
  ["Thudeo0710","tiktok","https://www.tiktok.com/@thudeo_0710","","CHƯA BOOK"],
  ["Cafe sữa ít sữa","tiktok","https://www.tiktok.com/@vythng99","","CHƯA BOOK | Cast: 400.000đ"],
  ["Chine Chine","tiktok","https://www.tiktok.com/@chinechine68778","","CHƯA BOOK"],
];

const stmt = db.prepare(`
  INSERT INTO "KOC" (id, ten, platform, follower, linkProfile, sdt, email, ghiChu, createdAt)
  VALUES (?, ?, ?, 0, ?, ?, NULL, ?, datetime('now'))
`);

let count = 0;
for (const [ten, platform, linkProfile, sdt, ghiChu] of kocs) {
  stmt.run(genId(), ten, platform, linkProfile, sdt, ghiChu);
  count++;
}

console.log(`✅ Đã nhập ${count} KOC vào database!`);
db.close();
